### ISSUE TITLE
Live2d Cubism 內 class 詢問

### ISSUE THREAD

**Issue by skysumbra** [Shikiotone/Shikiotone.Github.io#3]
你好
由於你使用的網站不能留言，按下登入後，會提示一個錯誤 [object ProgressEvent]
所以想在這請教
1.用 CEAA 字串定位，文中提到慢慢找，是找到含有CEAA 的檔案為止嗎?
2.文中Java字節(Byte) return false 的16進制是03AC，這是要如何看? 直接遭將return false 轉換成16 進制嗎?
3.不知道可不可以改程式zh-cn 字串成zh-tw

**Comment by Shikiotone** [comment]
其實那篇文章我沒認真寫完 導致邏輯有問題 看了也沒啥用 如果你只是想破解可以直接跳到最後一步


1.ceaa在a/c的包裡面 相當於定義了一個全局字符串數組 然後使用a/b內的a（int index）方法讀取字符串
 然後你自己數一下激活相關字符串的index看看是誰調用了這個方法就行了 後面就是不斷找引用直到找到激活驗證
2.字節碼規範裡面寫著的https://en.wikibooks.org/wiki/Java_Programming/Byte_Code
3.程序Live2D_Cubism.jar\res\i18n中包含了語言文件 你可以直接用工具將簡體翻譯為繁體

**Comment by Shikiotone** [comment]
> 你好
> 由於你使用的網站不能留言，按下登入後，會提示一個錯誤 [object ProgressEvent]
> 所以想在這請教
> 1.用 CEAA 字串定位，文中提到慢慢找，是找到含有CEAA 的檔案為止嗎?
> 2.文中Java字節(Byte) return false 的16進制是03AC，這是要如何看? 直接遭將return false 轉換成16 進制嗎?
> 3.不知道可不可以改程式zh-cn 字串成zh-tw
其實那篇文章我沒認真寫完 導致邏輯有問題 看了也沒啥用 如果你只是想破解可以直接跳到最後一步


1.ceaa在a/c的包裡面 相當於定義了一個全局字符串數組 然後使用a/b內的a（int index）方法讀取字符串
 然後你自己數一下激活相關字符串的index看看是誰調用了這個方法就行了 後面就是不斷找引用直到找到激活驗證
2.字節碼規範裡面寫著的https://en.wikibooks.org/wiki/Java_Programming/Byte_Code
3.程序Live2D_Cubism.jar\res\i18n中包含了語言文件 你可以直接用工具將簡體翻譯為繁體

**Comment by Shikiotone** [comment]
> 你好
> 由於你使用的網站不能留言，按下登入後，會提示一個錯誤 [object ProgressEvent]
> 所以想在這請教
> 1.用 CEAA 字串定位，文中提到慢慢找，是找到含有CEAA 的檔案為止嗎?
> 2.文中Java字節(Byte) return false 的16進制是03AC，這是要如何看? 直接遭將return false 轉換成16 進制嗎?
> 3.不知道可不可以改程式zh-cn 字串成zh-tw

其實那篇文章我沒認真寫完 導致邏輯有問題 看了也沒啥用 如果你只是想破解可以直接跳到最後一步

1.ceaa在a/c的包裡面 相當於定義了一個全局字符串數組 然後使用a/b內的a（int index）方法讀取字符串
然後你自己數一下激活相關字符串的index看看是誰調用了這個方法就行了 後面就是不斷找引用直到找到激活驗證
2.字節碼規範裡面寫著的https://en.wikibooks.org/wiki/Java_Programming/Byte_Code
3.程序Live2D_Cubism.jar\res\i18n中包含了語言文件 你可以直接用工具將簡體翻譯為繁體

**Comment by skysumbra** [comment]
1.再根據1，那這樣找的行為假設都是java 的話，如android APK的java 應該也是有可能?
2.再根據2，啟用某功能的判斷，如果直接改成 return true 是不是也有可能直接成立?

**Comment by Shikiotone** [comment]
> 1.再根據1，那這樣找的行為假設都是java 的話，如android APK的java 應該也是有可能?
> 2.再根據2，啟用某功能的判斷，如果直接改成 return true 是不是也有可能直接成立?

1.Java破解就是這麽簡單的事情 沒你想得那麽難 主要是看你有沒有耐心而已
2.根據情況還是有很多不同的 不是所有軟件都用bool判斷是否激活的 不過大部分情況下你可以直接嘗試把所有false改成true 如果可行就開始用篩選法直到找到激活的判斷

**Comment by skysumbra** [comment]
.嘗試練習一下，真的要找出正確的檔案與其位置，真的不容易，尤其是class 名稱和fun 名稱也相同時

**Comment by Shikiotone** [comment]
> .嘗試練習一下，真的要找出正確的檔案與其位置，真的不容易，尤其是class 名稱和fun 名稱也相同時

[https://i.loli.net/2020/09/12/241pFIbq76NLeiE.png](url) 名稱一樣根本無所謂 找到相關目錄是很簡單的 只是定位比較麻煩而已

**Comment by Shikiotone** [comment]
> .嘗試練習一下，真的要找出正確的檔案與其位置，真的不容易，尤其是class 名稱和fun 名稱也相同時

![1](https://user-images.githubusercontent.com/51998329/92971021-a787a300-f4ba-11ea-8220-5682a10b3954.png)
 名稱一樣根本無所謂 找到相關目錄是很簡單的 只是定位比較麻煩而已
